### ISSUE TITLE
[pixie-bundle]Fix pixie search formatting

### ISSUE THREAD

**Issue by tacman** [survos/survos#46]
https://mus.wip/en/pixie/pixie/

![image](https://github.com/user-attachments/assets/b0a4c9d0-b31e-43fe-b232-1b103da56fa7)

The "show counts" doesn't work, but I can fix that later.  This issue is that the formatting isn't attractive.  

Eventually we many want to put simple dropdown searches as well, but the form should all be one one line, not stacked.

**Comment by raj3292** [comment]
@tacman Have fixed this design issue and pushed code in the survos:rk branch.
