### ISSUE TITLE
[pixie-bundle] dropdown link doesn't work

### ISSUE THREAD

**Issue by tacman** [survos/survos#47]
![image](https://github.com/user-attachments/assets/5938d025-7bb0-4178-af7e-df2724108f8c)

https://mus.wip/en/pixie/pixie/

The dropdown link to the right of the table name (e..g. mapa) currently doesn't work.

**Comment by raj3292** [comment]
@tacman So i need to add 2 options with links of table and mieli in the right side dropdown. Is that correct?

**Comment by raj3292** [comment]
Done the changes by adding dropdown options.
Push code in the survos:rk branch.

**Comment by tacman** [comment]
works now, I added 'schema', which should really be admin-only.
