### ISSUE TITLE
[bootstrap-bundle] language dropdown could be formatted better

### ISSUE THREAD

**Issue by tacman** [survos/survos#48]
![image](https://github.com/user-attachments/assets/bd4edde9-207a-4a94-b250-b26d7ea3c887)

Perhaps those can be aligned and maybe different sizes for the name in the locale and the languages name in its own locale.

The file is _navbar_language_dropdown.html.twig in bootstrap-bundle

Code should only be visible in small screen, language name if large screen.  And maybe just the icon if a tiny screen?

**Comment by raj3292** [comment]
@tacman Have fixed the issue to show English in large screen and En in small screen.
Push in the survos:rk branch.

**Comment by tacman** [comment]
Yep, it's working, but the small screen also seems to trigger the menu
collapse.  We probably need to rethink the navbar a bit.
