### ISSUE TITLE
Use ux_icons instead of embedding the svg

### ISSUE THREAD

**Issue by tacman** [survos/survos#51]
Find icons at https://ux.symfony.com/icons

Then use them:
```twig
                {{ ux_icon('bi:geo-alt', {width:"30px"}) }}
```

instead of
```html
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi me-1 bi-geo-alt" viewBox="0 0 16 16">
                        <path d="M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A32 32 0 0 1 8 14.58a32 32 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10"/>
                        <path d="M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4m0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                    </svg>
```

**Comment by tacman** [comment]
We can then make a map of icons, e.g.

```twig
    {% set iconMap = {
        region: 'bi:geo-alt',
        culture: 'game-icons:luchador',
        floor: 'bi:bounding-box'
    } %}


    {% for var in ['dynasty','reign','culture','style','medium','technique'] %}
        {% set value = attribute(data,var)|default(false) %}
```

In reality, these from from other place, but are not yet incorporated into pixie.  


![Image](https://github.com/user-attachments/assets/2ad2dfbf-c708-4e34-82ee-34f624856a7a)

**Comment by raj3292** [comment]
@tacman I have updated design and push code. You need to add some icons and details first also can be able to make separate to 2 columns if possible to can set properly. Also data should be able to adjust above or down order so I can design properly.

**Comment by tacman** [comment]
icon map still needs some work, but i'll close this since embedded icons are gone.
